all: divide sqrt sqrt2 prime mergesort fibonacci maxhightofbinarytree maxhightofbinarytree quicksort permutation

permutation: permutation.c
	clang -o permutation permutation.c

divide: divide.c
	clang -o divide divide.c

quicksort: quicksort.c
	clang -o quicksort quicksort.c

sqrt: sqrt.c
	clang -o sqrt sqrt.c

sqrt2: sqrt2.c
	clang -o sqrt2 sqrt.c

prime: prime.c
	clang -o prime prime.c

mergesort: mergesort.c
	clang -o mergesort mergesort.c

fibonacci: fibonacci.c
	clang -o fibonacci fibonacci.c

maxhightofbinarytree: maxhightofbinarytree.c
	clang -o maxhightofbinarytree maxhightofbinarytree.c


stringmultiply: stringmultiply.c
	clang -o stringmultiply stringmultiply.c

TreeTraversal.class: TreeTraversal.java
	rm -f TreeTraversal.class
	javac TreeTraversal.java

test_TreeTraversal: TreeTraversal.class
	java TreeTraversal

MaxPathInTree.class: MaxPathInTree.java
	rm -f MaxPathInTree.class
	javac MaxPathInTree.java

test_MaxPathInTree: MaxPathInTree.class
	java MaxPathInTree
	
ThreeSum.class: ThreeSum.java
	rm -f ThreeSum.class
	javac ThreeSum.java

test_ThreeSum: ThreeSum.class
	java ThreeSum

VerticalSumInBinaryTree.class: VerticalSumInBinaryTree.java
	rm -f VerticalSumInBinaryTree.class
	javac VerticalSumInBinaryTree.java

test_VerticalSumInBinaryTree: VerticalSumInBinaryTree.class
	java VerticalSumInBinaryTree	
	
PrintAllRootToLeafPaths.class: PrintAllRootToLeafPaths.java
	rm -f PrintAllRootToLeafPaths.class
	javac PrintAllRootToLeafPaths.java

test_PrintAllRootToLeafPaths: PrintAllRootToLeafPaths.class
	java PrintAllRootToLeafPaths
	
VerifyBinaryTree.class: VerifyBinaryTree.java
	rm -f VerifyBinaryTree.class
	javac VerifyBinaryTree.java

test_VerifyBinaryTree: VerifyBinaryTree.class
	java VerifyBinaryTree
	
BestCombinationFinder.class: BestCombinationFinder.java
	rm -f BestCombinationFinder.class
	javac BestCombinationFinder.java

test_BestCombinationFinder: BestCombinationFinder.class
	java BestCombinationFinder

clean:
	rm -f *.class sqrt sqrt2 prime mergesort fibonacci maxhightofbinarytree maxhightofbinarytree stringmultiply quicksort  permutation divide 
