compile:
	javac *.java

checkstyle:
	checkstyle *.java

findbugs:
	findbugs *.class

zip:
	zip collinear.zip Point.java Brute.java Fast.java

clean:
	rm -f *.class

test1:
	java PointPlotter ./txt/input56.txt

brute6:
	java Brute ./txt/input6.txt

brute8:
	java Brute ./txt/input8.txt

brute10:
	java Brute ./txt/input10.txt

brute20:
	java Brute ./txt/input20.txt

brute40:
	java Brute ./txt/input40.txt

brute50:
	java Brute ./txt/input50.txt

brute56:
	java Brute ./txt/input56.txt

fast6:
	java Fast ./txt/input6.txt

fast8:
	java Fast ./txt/input8.txt
